/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseHeader: typeof import('./components/layouts/BaseHeader.vue')['default']
    BaseSide: typeof import('./components/layouts/BaseSide.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElText: typeof import('element-plus/es')['ElText']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    Logos: typeof import('./components/Logos.vue')['default']
    MyProduct: typeof import('./components/MyProduct.vue')['default']
    MyProductForm: typeof import('./components/MyProductForm.vue')['default']
    MyProducts: typeof import('./components/pages/MyProducts.vue')['default']
    MyProductsPage: typeof import('./components/pages/MyProductsPage.vue')['default']
    Profile: typeof import('./components/pages/Profile.vue')['default']
    Register: typeof import('./components/pages/Register.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignIn: typeof import('./components/pages/SignIn.vue')['default']
    TestProdact: typeof import('./components/pages/testProdact.vue')['default']
    TheApolloTest: typeof import('./components/TheApolloTest.vue')['default']
    TheFormProd: typeof import('./components/pages/TheFormProd.vue')['default']
    TheHomePage: typeof import('./components/pages/TheHomePage.vue')['default']
    TheLogin: typeof import('./components/TheLogin.vue')['default']
    TheModal: typeof import('./components/pages/TheModal.vue')['default']
    TheNavbar: typeof import('./components/layouts/TheNavbar.vue')['default']
    TheProduct: typeof import('./components/TheProduct.vue')['default']
    TheProductForm: typeof import('./components/TheProductForm.vue')['default']
    TheProductMainForm: typeof import('./components/pages/TheProductMainForm.vue')['default']
    TheProductMainPage: typeof import('./components/pages/TheProductMainPage.vue')['default']
    TheProductPage: typeof import('./components/pages/TheProductPage.vue')['default']
    TheProductPrewPage: typeof import('./components/pages/TheProductPrewPage.vue')['default']
    TheProductsPage: typeof import('./components/pages/TheProductsPage.vue')['default']
    TheRegisterPage: typeof import('./components/pages/TheRegisterPage.vue')['default']
  }
}
